name: YubiKitTests

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build for device
        run: |
          cd YubiKit
          ./build.sh
          cd ..
                        
      - name: Test on emulator
        run: |
          xcodebuild -sdk iphonesimulator -workspace YubiKit.xcworkspace -scheme YubiKit -destination "platform=iOS Simulator,OS=13.2.2,name=iPhone 8" test | xcpretty --test --color
         
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: yubikit-ios
          path: releases
          
  tests:
    needs: build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Test on device
        run: |
          xcodebuild -sdk iphoneos -workspace YubiKit.xcworkspace -scheme YubiKitFullStackTests -destination "platform=iOS,name=Irina’s iPhone" test | xcpretty --test --color



